baseURL = "https://meerasundar.netlify.app/"
Theme = "hugo-theme-nix"



[params]
      Name = "Meera Sundar"
      HeaderUsername = "Meera"
      HeaderHostname = "Web"
      About = "Hi there!"  
        GithubID = "meerasndr"
        TwitterID = "meerasndr"

# Main menu which appears below site header.
[menu]
      [[menu.header]]
      name = "posts"
      weight = 1
      url = "/posts"
      [[menu.header]]
      name = "bookmarks"
      weight = 2
      url = "/bookmarks"

