baseURL = "https://meerasundar.netlify.app/"
Theme = "hugo-theme-nix"
title = "Meera Sundar"

[params]
      Name = "Meera Sundar"
      HeaderUsername = "Meera"
      HeaderHostname = "Web"
        GithubID = "meerasndr"
        TwitterID = "meerasndr"
        SoundCloudID = "meerasndr"

# Main menu which appears below site header.
[menu]
      [[menu.header]]
      name = "posts"
      weight = 1
      url = "/posts"
      [[menu.header]]
      name = "music"
      weight = 2
      url = "/music"
      [[menu.header]]
      name = "bookmarks"
      weight = 3
      url = "/bookmarks"

