baseURL = "https://meerasundar.netlify.app/"
languageCode = "en-us"
theme = "etch"
title = "Meera Sundar"


[params]
  description = "Your site description"
  copyright = "Copyright © 2020 Meera Sundar"
  dark = "auto"
  highlight = true
# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.




[permalinks]
  posts = "/:title/"

[markup.goldmark.renderer]
  # Allow HTML in Markdown
  unsafe = true

  [markup.tableOfContents]
    ordered = true
