baseURL = "https://meerasundar.netlify.app/"
languageCode = "en-us"
title = "Meera Sundar"
theme = "minimal"

[params]
    author = "Meera Sundar"
    description = "Developer. Musician."
    githubUsername = "meerasndr"
    accent = "red"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 2

[[menu.main]]
    url = "/posts/"
    name = "Posts"
    weight = 3

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "https://github.com/meerasndr/"
    name = "github"
    weight = 1

[[menu.icon]]
    url = "https://twitter.com/latticebridge/"
    name = "twitter"
    weight = 2

[[menu.icon]]
    url = "https://stackoverflow.com/users/11915985/meera"
    name = "stack-overflow"
    weight = 3
