baseURL = "https://meerasundar.netlify.app/"
languageCode = "en-us"
theme = "etch"
title = "Meera Sundar"


[params]
  description = "Your site description"
  copyright = "Copyright © 2020 Meera Sundar"
  dark = "auto"
  highlight = true
# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[params.social]]
  icon = "github"
  url = "https://github.com/meerasndr/"

[[params.social]]
  icon = "twitter"
  url = "https://twitter.com/meerasndr/"

[[params.social]]
    icon = "stack-overflow"
    url = "https://stackoverflow.com/users/11915985/meera"

[[params.social]]
  icon = "soundcloud"
  url = "https://soundcloud.com/meerasndr"

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "posts"
    title = "posts"
    url = "/"
    weight = 10

  [[menu.main]]
    identifier = "about"
    name = "about"
    title = "about"
    url = "/about/"
    weight = 20

[permalinks]
  posts = "/:title/"

[markup.goldmark.renderer]
  # Allow HTML in Markdown
  unsafe = true

  [markup.tableOfContents]
    ordered = true
